export const products = [
  {
    id: 1,
    name: "Laptop",
    price: 1200,
    category: "Electronics",
    stock: 15,
    image: "https://picsum.photos/200/300",
    isAction: true,
  },
  {
    id: 2,
    name: "Phone",
    price: 800,
    category: "Electronics",
    stock: 30,
    image: "https://picsum.photos/200/300",
    isAction: true,
  },
  {
    id: 3,
    name: "Headphones",
    price: 150,
    category: "Accessories",
    stock: 50,
    image: "https://picsum.photos/200/300",
    isAction: true,
  },
  {
    id: 4,
    name: "Smart Watch",
    price: 250,
    category: "Wearables",
    stock: 20,
    image: "https://picsum.photos/200/300",
    isAction: true,
  },
  {
    id: 5,
    name: "Smart Watch",
    price: 250,
    category: "Wearables",
    stock: 20,
    image: "https://picsum.photos/200/300",
    isAction: true,
  },
  {
    id: 7,
    name: "Smart Watch",
    price: 250,
    category: "Wearables",
    stock: 20,
    image: "https://picsum.photos/200/300",
    isAction: true,
  },
  {
    id: 10,
    name: "Smart Watch",
    price: 250,
    category: "Wearables",
    stock: 20,
    image: "https://picsum.photos/200/300",
    isAction: true,
  },
  {
    id: 11,
    name: "Smart Watch",
    price: 250,
    category: "Wearables",
    stock: 20,
    image: "https://picsum.photos/200/300",
    isAction: true,
  },
];
